### ISSUE TITLE
[BUG] Error somewhere in reporting

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/dashboards-reporting#151]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at _callee4$ (reportsDashboards.plugin.js:24:201073)
    at tryCatch (reportsDashboards.plugin.js:24:180012)
    at Generator.invoke [as _invoke] (reportsDashboards.plugin.js:24:183963)
    at Generator.next (reportsDashboards.plugin.js:24:181151)
    at asyncGeneratorStep (reportsDashboards.plugin.js:1:73707)
    at _next (reportsDashboards.plugin.js:1:74018)
    at reportsDashboards.plugin.js:1:74168
    at new Promise (<anonymous>)
    at reportsDashboards.plugin.js:1:73930
    at checkURLParams (reportsDashboards.plugin.js:24:202215)
_callee4$ @ reportsDashboards.plugin.js:24
tryCatch @ reportsDashboards.plugin.js:24
invoke @ reportsDashboards.plugin.js:24
(anonymous) @ reportsDashboards.plugin.js:24
asyncGeneratorStep @ reportsDashboards.plugin.js:1
_next @ reportsDashboards.plugin.js:1
(anonymous) @ reportsDashboards.plugin.js:1
(anonymous) @ reportsDashboards.plugin.js:1
checkURLParams @ reportsDashboards.plugin.js:24
(anonymous) @ reportsDashboards.plugin.js:24
u @ osd-ui-shared-deps.js:406
l @ osd-ui-shared-deps.js:406
setTimeout (async)
(anonymous) @ osd-ui-shared-deps.js:406
c @ osd-ui-shared-deps.js:406
add @ osd-ui-shared-deps.js:406
(anonymous) @ osd-ui-shared-deps.js:406
Deferred @ osd-ui-shared-deps.js:406
then @ osd-ui-shared-deps.js:406
_.fn.ready @ osd-ui-shared-deps.js:406
_.fn.init @ osd-ui-shared-deps.js:406
_ @ osd-ui-shared-deps.js:395
(anonymous) @ reportsDashboards.plugin.js:24
__webpack_require__ @ reportsDashboards.plugin.js:1
(anonymous) @ reportsDashboards.plugin.js:24
__webpack_require__ @ reportsDashboards.plugin.js:1
(anonymous) @ reportsDashboards.plugin.js:24
__webpack_require__ @ reportsDashboards.plugin.js:1
get @ bootstrap.js:28
read @ core.entry.js:15
_callee3$ @ core.entry.js:15
tryCatch @ securityAnalyticsDashboards.plugin.js:2
(anonymous) @ securityAnalyticsDashboards.plugin.js:2
(anonymous) @ securityAnalyticsDashboards.plugin.js:2
plugin_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
(anonymous) @ core.entry.js:15
(anonymous) @ core.entry.js:15
createPluginInstance @ core.entry.js:15
_callee$ @ core.entry.js:15
tryCatch @ securityAnalyticsDashboards.plugin.js:2
(anonymous) @ securityAnalyticsDashboards.plugin.js:2
(anonymous) @ securityAnalyticsDashboards.plugin.js:2
plugin_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
(anonymous) @ core.entry.js:15
(anonymous) @ core.entry.js:15
setup @ core.entry.js:15
_callee$ @ core.entry.js:15
u @ osd-ui-shared-deps.js:382
(anonymous) @ osd-ui-shared-deps.js:382
(anonymous) @ osd-ui-shared-deps.js:382
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
plugins_service_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
(anonymous) @ core.entry.js:15
(anonymous) @ core.entry.js:15
setup @ core.entry.js:15
_callee$ @ core.entry.js:15
u @ osd-ui-shared-deps.js:382
(anonymous) @ osd-ui-shared-deps.js:382
(anonymous) @ osd-ui-shared-deps.js:382
core_system_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
core_system_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
(anonymous) @ core.entry.js:15
(anonymous) @ core.entry.js:15
setup @ core.entry.js:15
_callee$ @ core.entry.js:15
u @ osd-ui-shared-deps.js:382
(anonymous) @ osd-ui-shared-deps.js:382
(anonymous) @ osd-ui-shared-deps.js:382
osd_bootstrap_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
Promise.then (async)
osd_bootstrap_asyncGeneratorStep @ core.entry.js:15
_next @ core.entry.js:15
(anonymous) @ core.entry.js:15
(anonymous) @ core.entry.js:15
_osdBootstrap__ @ core.entry.js:15
__osdBootstrap__ @ core.entry.js:15
(anonymous) @ bootstrap.js:166
innerCb @ bootstrap.js:91
load (async)
loadScript @ bootstrap.js:81
(anonymous) @ bootstrap.js:100
load @ bootstrap.js:87
window.onload @ bootstrap.js:105
load (async)
(anonymous) @ bootstrap.js:48
core.entry.js:15 TypeError: Cannot read properties of undefined (reading 'call')
    at __webpack_require__ (observabilityDashboards.plugin.js:1:932)

**Comment by derek-ho** [comment]
Cannot reproduce again
