### ISSUE TITLE
[BUG] Failure during the running of `yarn osd bootstrap`

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/dashboards-reporting#263]
**What is the bug?**
Here is the error log from GHA
```
warning " > ts-jest@29.1.1" has unmet peer dependency "jest@^29.0.0".
warning " > ts-jest@29.1.1" has unmet peer dependency "typescript@>=4.3 <6".
error Error: ENOENT: no such file or directory, lstat '/home/runner/work/dashboards-reporting/dashboards-reporting/OpenSearch-Dashboards/packages/osd-eslint-import-resolver-opensearch-dashboards/node_modules/resolve'
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: /opt/hostedtoolcache/node/18.16.0/x64/lib/node_modules/yarn/bin/yarn.js install --non-interactive
          at makeError (/home/runner/work/dashboards-reporting/dashboards-reporting/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:26622:11)
          at handlePromise (/home/runner/work/dashboards-reporting/dashboards-reporting/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:25558:26)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async installInDir (/home/runner/work/dashboards-reporting/dashboards-reporting/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:25298:3)
          at async Project.installDependencies (/home/runner/work/dashboards-reporting/dashboards-reporting/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:[150](https://github.com/opensearch-project/dashboards-reporting/actions/runs/7228337751/job/19697602474?pr=262#step:17:151)53:5)
          at async Object.run (/home/runner/work/dashboards-reporting/dashboards-reporting/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:9089:11)
          at async runCommand (/home/runner/work/dashboards-reporting/dashboards-reporting/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:57802:5)
          at async Object.run (/home/runner/work/dashboards-reporting/dashboards-reporting/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:257:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
During the development of the cypress CI workflow, I observed that the above error happens during the bootstrap step of OSD. However, if you retry the bootstrap command, the entire procedure will pass without a single error. (Reference to [comment](https://github.com/opensearch-project/dashboards-reporting/pull/262#discussion_r1428616356))

This error constantly happening on GHA and local setup.

**How can one reproduce the bug?**
- Install Dashboards reporting plugin into OSD and run `yarn osd bootstrap`

**What is the expected behavior?**
Passing without any error

**What is your host/environment?**
- main branch

**Comment by ruanyl** [comment]
Having the same issue when assembling OSD distribution, `yarn osd bootstrap` failed the first time it run, but succeed the with another try.

**Comment by ruanyl** [comment]
This seems to break the build of opensearch-dashboards distribution with https://github.com/opensearch-project/opensearch-build, post my findings here:

In the build script, when a plugin build successfully, that plugin source code folder will then be removed. However, when getting errors, the source code folder of reportsDashboards didn't get removed.

This causes `single_version_dependencies` issue when used together with `--continue-on-error` as then multiple plugins will be pulled into the plugins folder.

```
ERROR [single_version_dependencies] Multiple version ranges for the same dependency
      were found declared across different package.json files. Please consolidate
      those to match across all package.json files. Different versions for the
      same dependency is not supported.

      If you have questions about this please reach out to the operations team.

      The conflicting dependencies are:

        cypress
          ^12.8 => reports-dashboards
          ^13.6.0 => opensearch-security-dashboards
```

**Comment by ruanyl** [comment]
This issue blocks functional test repo: https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/985

**Comment by RyanL1997** [comment]
Hi @ruanyl, thanks for providing more findings. Yes, I think for fixing the distribution failure we had 4 PRs in all the insights repos (dashboards-observability, reporting, visualization, and query-workbench) to sync the versions of these dependencies:
- [x] query-workbench: https://github.com/opensearch-project/dashboards-query-workbench/pull/241
- [x] dashboards-observability: https://github.com/opensearch-project/dashboards-observability/pull/1342
- [x] visualization: https://github.com/opensearch-project/dashboards-visualizations/pull/310
- [x] reporting: https://github.com/opensearch-project/dashboards-reporting/pull/268

But I in the error msg of distribution build failure, both @derek-ho [1] and @cwperks [2] also found out that there are some of the other components needs to align their dependencies.

Reference:
[1]: https://github.com/opensearch-project/dashboards-query-workbench/issues/240
[2]: https://github.com/opensearch-project/dashboards-query-workbench/pull/232#issuecomment-1881517979

**Comment by joshuali925** [comment]
not sure how you upgraded yarn.lock in #268? i did `rm yarn.lock`, somehow `yarn upgrade` didn't fix this

**Comment by RyanL1997** [comment]
@joshuali925 Thanks for the info! I think I updated that in the above PR, but I will double check it to see if we can safely remove the retries in our CI workflow.

**Comment by derek-ho** [comment]
@joshuali925 @RyanL1997 did you folks bootstrap with multiple plugins? I see different errors for multiple plugins, but it seems like there is also a windows failure, not sure if its related: https://build.ci.opensearch.org/blue/rest/organizations/jenkins/pipelines/distribution-build-opensearch-dashboards/runs/6871/nodes/76/steps/303/log/?start=0, either way there are a few issues here I think, not sure if it is only in this repo or not.

**Comment by RyanL1997** [comment]
For this thread I think it is just for the dashboards-reporting. And the PR #270 just fixed that. However, according to what we did to this repo, if there are multiple issues on the bootstrap, we recommended to update the `yarn.lock` first and to see if it fixes the issue.

**Comment by joshuali925** [comment]
@derek-ho the error log says that the cause was outdated dependency name
```
Error: Cannot find module '@babel/plugin-proposal-class-properties'
```

it should be `@babel/plugin-transform-xxx`, see https://github.com/opensearch-project/OpenSearch-Dashboards/commit/b82aa1ccb513cb3d3ba1609195842cac9f428233#diff-caf8141894faf58ab4b0f923a3387a3acfc3de01b9f1b38c7923f40772cfc31aL41
