### ISSUE TITLE
OpenSearch dashboards report generate is not working

### ISSUE THREAD

**Issue by pmhanaga** [opensearch-project/dashboards-reporting#302]
Versions (relevant - OpenSearch/Dashboard/Server OS/Browser):

opensearch-dashboards:v2.3.0

Describe the issue:

All OpenSearch pods are up and running:

But OpenSearch dashboards report generate is not working

When try to generate report we are seeing attached error screen and attached logs.

In pod we are seeing error like “no handler found for uri [/_plugins/_reports/on_demand” as below.

[“error”,“plugins”,“reportsDashboards”],“pid”:7,“message”:"Failed to generate report: no handler found for uri [/_plugins/_reports/on_demand]

We are just trying to understand is there any configuration missing while installing occne or open search.

Or is there any pre-request steps need to do before generating report.

even Create report definition also giving same kind of error.
[Open Search dashboard pod logs.txt](https://github.com/opensearch-project/OpenSearch-Dashboards/files/14135300/Open.Search.dashboard.pod.logs.txt)
![OpenSearch Error Screen](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/49629867/e2a60bc7-f5dc-4605-8a19-a74c295e7337)

**Comment by Swiddis** [comment]
Are all of the plugins installed on the OpenSearch pods? This is a somewhat generic error that roughly equates "Reporting isn't installed", it's hard to debug without more information about the setup.

**Comment by pburkholder** [comment]
Hi -- Same error, different setup. 

I'm doing the setup following DEVELOPER_GUIDE.md for OpenSearch, OpenSearch Dashboards, and dashboards-reporting, so I have the following checked out:

```
OpenSearch
OpenSearch-Dashboards
├── plugins
├──────dashboards-reporting
```

I then run OpenSearch with 
```
./gradlew run
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.10.2
  OS Info               : Mac OS X 14.7.2 (aarch64)
  JDK Version           : 21 (Eclipse Temurin JDK)
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
  Random Testing Seed   : 60656472541EC171
  In FIPS 140 mode      : false
=======================================
```

And OpenSearch Dashboards with
```
❯ yarn start
yarn run v1.22.22
$ scripts/use_node scripts/opensearch_dashboards --dev
```

From there, I'm able to use  load sample weblog data at http://0.0.0.0:5603/xoy, and save a search. When I go to the "Reporting Menu" I have valid options for downloading a CSV:

![image](https://github.com/user-attachments/assets/185c4453-087a-4e64-8b37-048bdbfdabcf)


but when I try to do so I get this error in the Dashboards log:

```
server    log   [20:59:32.050] [error][plugins][reportsDashboards] Failed to generate report: no handler found for uri [/_plugins/_reports/on_demand] and method [PUT] :: {"path":"/_plugins/_reports/on_demand","query":{},"body":"{\"beginTimeMs\":1735246771996,\"endTimeMs\":1735851571996,\"reportDefinitionDetails\":{\"id\":\"76d9d6e0-c94c-11ef-b18d-314511f86852\",\"lastUpdatedTimeMs\":1735851572046,\"createdTimeMs\":1735851572046,\"reportDefinition\":{\"name\":\"On_demand_report\",\"isEnabled\":true,\"source\":{\"description\":\"In-context report download\",\"type\":\"SavedSearch\",\"id\":\"498539a0-c94c-11ef-a12b-77ad3f2669a3\",\"origin\":\"http://0.0.0.0:5603/xoy\"},\"format\":{\"duration\":\"PT168H\",\"fileFormat\":\"Csv\",\"limit\":10000},\"trigger\":{\"triggerType\":\"Download\"},\"delivery\":{\"configIds\":[\"\"],\"title\":\"\",\"textDescription\":\"\",\"htmlDescription\":\"\"}}},\"status\":\"Success\",\"inContextDownloadUrlPath\":\"/app/data-explorer/discover#/view/498539a0-c94c-11ef-a12b-77ad3f2669a3?_q=(filters:!(),query:(language:kuery,query:''))&_a=(discover:(columns:!(agent),isDirty:!f,savedSearch:'498539a0-c94c-11ef-a12b-77ad3f2669a3',sort:!()),metadata:(indexPattern:'90943e30-9a47-11e8-b64d-95841ca0b247',view:discover))&_g=(filters:!(),refreshInterval:(pause:!f,value:900000),time:(from:'2024-12-26T20:59:31.999Z',to:'2025-01-02T20:59:31.999Z'))\"}","statusCode":400,"response":"{\"error\":\"no handler found for uri [/_plugins/_reports/on_demand] and method [PUT]\"}"}
server    log   [20:59:32.051] [error][plugins][reportsDashboards] StatusCodeError: no handler found for uri [/_plugins/_reports/on_demand] and method [PUT]
    at respond (/Users/peterdburkholder/Projects/misc/OpenSearch-Dashboards/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/Users/peterdburkholder/Projects/misc/OpenSearch-Dashboards/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/Users/peterdburkholder/Projects/misc/OpenSearch-Dashboards/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/Users/peterdburkholder/Projects/misc/OpenSearch-Dashboards/node_modules/lodash/lodash.js:4991:19)
    at IncomingMessage.emit (node:events:529:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  status: 400,
  displayName: 'BadRequest',
  path: '/_plugins/_reports/on_demand',
  query: {},
  body: {
    error: 'no handler found for uri [/_plugins/_reports/on_demand] and method [PUT]'
  },
  statusCode: 400,
  response: '{"error":"no handler found for uri [/_plugins/_reports/on_demand] and method [PUT]"}',
  toString: [Function (anonymous)],
  toJSON: [Function (anonymous)]
```

So: is there something I should be doing different to get the reporting plugin to work when in a developer environment? Thanks!

**Comment by singlelius** [comment]
i met the same error,have you solve this problem? @pburkholder
